from backtesterRB30.libs.utils.config_validator import validate_config
from backtesterRB30.libs.utils.historical_sources import EXANTE_INTERVALS, HISTORICAL_SOURCES, BINANCE_INTERVALS, DUKASCOPY_INTERVALS, COINGECKO_INTERVALS
from datetime import datetime